Name:           ros-indigo-velodyne-simulator
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS velodyne_simulator package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/velodyne_simulator
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-velodyne-description
Requires:       ros-indigo-velodyne-gazebo-plugins
BuildRequires:  ros-indigo-catkin

%description
Metapackage allowing easy installation of Velodyne simulation components.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Feb 04 2016 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 0.0.2-0
- Autogenerated by Bloom

* Thu Feb 04 2016 Kevin Hallenbeck <khallenbeck@dataspeedinc.com> - 1.0.2-0
- Autogenerated by Bloom

